<a href="https://colab.research.google.com/github/y-nagayoshi/Python-Data-Science-Handbook-2nd-Edition/blob/main/5%E7%AB%A0_NumPy%E9%85%8D%E5%88%97%E3%81%AE%E5%9F%BA%E7%A4%8E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3,4))
x3 = rng.integers(10, size=(3,4,5))


In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


In [3]:
x1[::2]

array([9, 0, 8])

In [4]:
x1[1::2]

array([4, 3, 6])

In [7]:
x2[:2, ::2]

array([[3, 3],
       [4, 2]])

In [6]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [8]:
x2[::-1, ::-1]

array([[9, 6, 0, 0],
       [3, 2, 0, 4],
       [7, 3, 1, 3]])

In [10]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[3, 1],
       [4, 0]])

In [13]:
grid = np.arange(1,10).reshape(3,3) # reshapeは元配列のビューを返す
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x = np.array([1, 2, 3])
x[np.newaxis, :]

array([[1, 2, 3]])

In [16]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [17]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [19]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
x1,x2,x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))