<a href="https://colab.research.google.com/github/y-nagayoshi/Python-Data-Science-Handbook-2nd-Edition/blob/main/6%E7%AB%A0_NumPy%E9%85%8D%E5%88%97%E3%81%AE%E8%A8%88%E7%AE%97%EF%BC%9A%E3%83%A6%E3%83%8B%E3%83%90%E3%83%BC%E3%82%B5%E3%83%AB%E9%96%A2%E6%95%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = rng.integers(1, 10, size=5)
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [2]:
big_array = rng.integers(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

2.01 s ± 436 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%timeit (1.0 / big_array)

1.9 ms ± 273 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [5]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [6]:
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])

In [9]:
x = [1,2,3]
np.power(3.5,x)

array([ 3.5  , 12.25 , 42.875])

In [11]:
x = [1,2,4,10]
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

In [12]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
y

array([ 0., 10., 20., 30., 40.])

In [13]:
y = np.zeros(10)
np.power(2,x,out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [18]:
x = np.arange(1,6)
np.add.reduce(x)

15